### ISSUE TITLE
Trying to run example app - Cannot call method 'replace' of undefined (handlebars)

### ISSUE THREAD

**Issue by warnero** [charlesjolley/node-ember#12]
I was trying to bump the version to the latest ember/data and I am running into this issue on my app and the example app:

/Users/warner/code/projects/node-ember/node_modules/handlebars/lib/handlebars/compiler/compiler.js:1147
      .replace(/\/g, '\\')
       ^
TypeError: Cannot call method 'replace' of undefined
    at Object.JavaScriptCompiler.quotedString (/Users/warner/code/projects/node-ember/node_modules/handlebars/lib/handlebars/compiler/compiler.js:1147:8)
    at Object.JavaScriptCompiler.setupHelper (/Users/warner/code/projects/node-ember/node_modules/handlebars/lib/handlebars/compiler/compiler.js:1164:61)
    at Object.JavaScriptCompiler.invokeHelper (/Users/warner/code/projects/node-ember/node_modules/handlebars/lib/handlebars/compiler/compiler.js:869:41)
    at Object.JavaScriptCompiler.compile (/Users/warner/code/projects/node-ember/node_modules/handlebars/lib/handlebars/compiler/compiler.js:490:29)
    at Object.JavaScriptCompiler.compileChildren (/Users/warner/code/projects/node-ember/node_modules/handlebars/lib/handlebars/compiler/compiler.js:982:49)
    at Object.JavaScriptCompiler.compile (/Users/warner/code/projects/node-ember/node_modules/handlebars/lib/handlebars/compiler/compiler.js:478:10)
    at Object.Ember.Handlebars.compile (/Users/warner/code/projects/node-ember/handlebars.js:171:66)
    at Ember.Handlebars.bootstrap.selectors (/Users/warner/code/projects/node-ember/handlebars.js:3261:37)
    at Object.<anonymous> (/Users/warner/code/projects/node-ember/handlebars.js:3521:3)
    at Module._compile (module.js:456:26)

Not having any luck in tracking it down so far.

**Comment by robhrt7** [comment]
Having the same issue as well with latest build.

**Comment by ghost** [comment]
same same

**Comment by drew-wallace** [comment]
Same. Using the contact example project from this repo on Node 0.10.25.
