### ISSUE TITLE
window is not defined error

### ISSUE THREAD

**Issue by farin** [charlesjolley/node-ember#6]
node_modules/ember/rsvp.js:215
 })(window.RSVP = {});
    ^
ReferenceError: window is not defined
    at .../node_modules/ember/rsvp.js:215:5
    at Object.<anonymous> (.../node_modules/ember/rsvp.js:217:3)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)

**Comment by MikeAski** [comment]
I think updating Ember would be sufficient as this is an RSVP issue which has already been fixed. Nevertheless, this is not yet packaged in an official Ember build, but available only in master... :-/

**Comment by ghost** [comment]
I've got the same error (pointed on the views module) while trying the contacts sample :+1: 

node server.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'window'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/tag-all/Workspace/Samples/node-ember-master/views.js:5:1)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)

**Comment by brian-gates** [comment]
I'm getting this issue as well.  Any chance of an update?

**Comment by ghost** [comment]
make an npm install in your root and in examples/contacts
